version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Batasi CPU untuk aplikasi Laravel
          memory: 3G   # Batasi penggunaan memori untuk aplikasi Laravel
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Batasi CPU untuk Nginx
          memory: 2G # Batasi penggunaan memori untuk Nginx
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pos-master
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2.0'  # Batasi CPU untuk MySQL
          memory: 2G   # Batasi penggunaan memori untuk MySQL
    sysctls:
      net.ipv4.tcp_fin_timeout: 30  # Optimasi parameter kernel
      # fs.file-max: 500000           # Tingkatkan batas file
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Batasi CPU untuk phpMyAdmin
          memory: 512M # Batasi penggunaan memori untuk phpMyAdmin
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
